# Generated by Django 5.1.7 on 2025-03-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Масса (кг)')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Длина (м)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ширина (м)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Высота (м)')),
                ('departure_point', models.CharField(max_length=255, verbose_name='Точка отправления')),
                ('destination_point', models.CharField(max_length=255, verbose_name='Точка прибытия')),
                ('departure_date', models.DateTimeField(verbose_name='Дата отправления')),
                ('arrival_date', models.DateTimeField(verbose_name='Дата прибытия')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
            },
        ),
    ]
